### ISSUE TITLE
1.1.0 not released to MavenCentral

### ISSUE THREAD

**Issue by mtrakal** [AckeeCZ/user-agent#3]
https://github.com/AckeeCZ/android-user-agent/runs/3583864894?check_suite_focus=true

From the log: 
```
 Task :releaseRepository
GET request failed. 404: , body: {"errors":[{"id":"*","msg":"No such repository: iogithubackeecz-1047"}]}
Requested operation was executed successfully in attempt 2 (maximum allowed 61)
```

Jitpack as alternative didn't build too, due to Java version incompatibility:
https://jitpack.io/#AckeeCZ/android-user-agent
https://jitpack.io/com/github/AckeeCZ/android-user-agent/v1.1.0/build.log

**Comment by davidbilik** [comment]
Hey @mtrakal, actually it was released to maven central 🤔 https://repo.maven.apache.org/maven2/io/github/ackeecz/user-agent/1.1.0/ The upload process to maven central is flaky a lot and that's why the plugin takes several attempts. You can see even in the log you pasted "Requested operation was executed successfully in attempt 2 (maximum allowed 61)" We don't use jitpack for our open source libraries so we did not check compatibility at all. Is it something we should investigate?
